/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-05-13 12:30:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Payment;

public final class Payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Payment");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Payment Management</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Views/bootstrap.min.css\"> \r\n");
      out.write("<script src=\"components/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"components/pay.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-md navbar-dark\" style=\"background-color: #638CC3\">\r\n");
      out.write("                   \r\n");
      out.write("	<ul class=\"navbar-nav\">\r\n");
      out.write("		<li><a href=\"Index.jsp\" class=\"nav-link\" style=\"font-family: cursive;\"> ELECTROGRID ONLINE SERVICE PLATFORM</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container\"> \r\n");
      out.write("	<div class=\"row\">  \r\n");
      out.write("    	<div class=\"container col-md-5\">\r\n");
      out.write("    	   <br><br><br>\r\n");
      out.write("        	<div class=\"card\">\r\n");
      out.write("            	<div class=\"card-body\">\r\n");
      out.write("                	<caption>\r\n");
      out.write("                    	<center><h2 style=\"font-family: Georgia, serif;\">\r\n");
      out.write("                        	Payment Management\r\n");
      out.write("                        </h2></center>\r\n");
      out.write("                 	</caption>  \r\n");
      out.write("                 	<br>\r\n");
      out.write("				\r\n");
      out.write("				<form id=\"formPayment\" name=\"formPayment\" method=\"post\" action=\"Payment.jsp\">  \r\n");
      out.write("				\r\n");
      out.write("					Payment Date:  \r\n");
      out.write("					<input id=\"PaymentDate\" name=\"PaymentDate\" type=\"text\" class=\"form-control form-control-sm\">  \r\n");
      out.write("					\r\n");
      out.write("					<br> \r\n");
      out.write("					Payment Type:  \r\n");
      out.write("					<input id=\"PaymentType\" name=\"PaymentType\" type=\"text\" class=\"form-control form-control-sm\">  \r\n");
      out.write("					\r\n");
      out.write("					<br>\r\n");
      out.write("					 Amount:  \r\n");
      out.write("					 <input id=\"Amount\" name=\"Amount\" type=\"text\" class=\"form-control form-control-sm\">  \r\n");
      out.write("					 \r\n");
      out.write("					 <br> \r\n");
      out.write("					 Card Number:  \r\n");
      out.write("					 <input id=\"CardNumber\" name=\"CardNumber\" type=\"text\" class=\"form-control form-control-sm\">  		 \r\n");
      out.write("					 \r\n");
      out.write("					 <br>  \r\n");
      out.write("					 <input id=\"btnSave\" name=\"btnSave\" type=\"button\" value=\"Save\" class=\"btn btn-primary\"style=\"background-color:#067fc9\">  \r\n");
      out.write("					 <input type=\"hidden\" id=\"hidPaymentIDSave\" name=\"hidPaymentIDSave\" value=\"\"> \r\n");
      out.write("					 \r\n");
      out.write("					 \r\n");
      out.write("				</form> \r\n");
      out.write("				     \r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<br>\r\n");
      out.write("				<div id=\"alertSuccess\" class=\"alert alert-success\"></div>  \r\n");
      out.write("		        <div id=\"alertError\" class=\"alert alert-danger\"></div> \r\n");
      out.write("		</div>\r\n");
      out.write("				\r\n");
      out.write("		\r\n");
      out.write("				\r\n");
      out.write("							\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("               \r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"container text-right\">\r\n");
      out.write("			    	<a href=\"Index.jsp\" class=\"btn btn-success\"style=\"background-color:#067fc9\">Navigate To Home page</a>\r\n");
      out.write("            	</div>\r\n");
      out.write("                <br><br>\r\n");
      out.write("            	<h3 class=\"text-center\" style=\"font-family: serif;\">Payment Details</h3>\r\n");
      out.write("                <hr>\r\n");
      out.write("                	<br>\r\n");
      out.write("                    <div id=\"divItemsGrid\">   \r\n");
      out.write("						");
    
					    	Payment paymentObj = new Payment();
							out.print(paymentObj.readPayment());   
						
      out.write("  \r\n");
      out.write("					\r\n");
      out.write("					<br><br><br>\r\n");
      out.write("					</div> \r\n");
      out.write("			</div>\r\n");
      out.write("		</div>			  \r\n");
      out.write("	</div>	 \r\n");
      out.write("</div>   \r\n");
      out.write("<br>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
